
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.IronPython.Gui
{
	public partial class MainPanel
	{
		private global::Gtk.VBox mainVBox;
		private global::Gtk.Label label1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Image fileEntryImage;
		private global::MonoDevelop.Components.FileEntry ironFileEntry;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.Label label2;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label7;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.Label informationLabel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.IronPython.Gui.MainPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.IronPython.Gui.MainPanel";
			// Container child MonoDevelop.IronPython.Gui.MainPanel.Gtk.Container+ContainerChild
			this.mainVBox = new global::Gtk.VBox ();
			this.mainVBox.Name = "mainVBox";
			this.mainVBox.BorderWidth = ((uint)(5));
			// Container child mainVBox.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("IronPython interpreter location\n");
			this.mainVBox.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.mainVBox [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child mainVBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fileEntryImage = new global::Gtk.Image ();
			this.fileEntryImage.Name = "fileEntryImage";
			this.hbox1.Add (this.fileEntryImage);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fileEntryImage]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ironFileEntry = new global::MonoDevelop.Components.FileEntry ();
			this.ironFileEntry.Name = "ironFileEntry";
			this.ironFileEntry.BrowserTitle = "Specify the interpreter to use";
			this.hbox1.Add (this.ironFileEntry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ironFileEntry]));
			w3.Position = 1;
			this.mainVBox.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.mainVBox [this.hbox1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child mainVBox.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (1F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(20));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<i>Specify the interpreter to use (like ipy or ipyw). Some versions of IronPython include an interpreter to be used in 64 bit architectures.</i>");
			this.label2.UseMarkup = true;
			this.label2.Wrap = true;
			this.alignment1.Add (this.label2);
			this.mainVBox.Add (this.alignment1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.mainVBox [this.alignment1]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			w6.Padding = ((uint)(6));
			// Container child mainVBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Runtime information</b>");
			this.label7.UseMarkup = true;
			this.vbox2.Add (this.label7);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label7]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.alignment2.LeftPadding = ((uint)(20));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.informationLabel = new global::Gtk.Label ();
			this.informationLabel.Name = "informationLabel";
			this.informationLabel.Xalign = 0F;
			this.informationLabel.UseMarkup = true;
			this.informationLabel.Wrap = true;
			this.alignment2.Add (this.informationLabel);
			this.vbox2.Add (this.alignment2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment2]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.mainVBox.Add (this.vbox2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.mainVBox [this.vbox2]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			w10.Padding = ((uint)(12));
			this.Add (this.mainVBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
